### PR TITLE
[WIP] miscellaneous style changes

### LINKED ISSUE #148: Remove 'license' and 'data' headers in step 2
- [x] Move 'Frequency of data' to the top
- [x] remove 'license' and 'data' headers

### PR DESCRIPTION
**Pull request by mkong0216**
- Added the raw images provided by openaddresses to public/assets/images 
- Added "This is a small sample of the data for preview" message in data-format page
- Updated MOD title to "Submit-UI" 
- Added error message styling to Intro page and Contact page 
- Added 150px of white space at end of each page 
- Added semi-transparent black background behind steps
- Changed color of paragraph and body text to #444 and placeholder text to #bfbfbf 
- Both "Choose from license" and "Provide link to license" displayed. Once user interacts with one, the corresponding radio button gets checked 
- Made "house number" field on data-format table narrower by making "house" and "number" on separate lines
- Capitalized true for attribution 
- Made edit link on Review page bold and same font-size as data-format table headers 
- Removed headers for More-Info page and moved "Frequency of update" to top (resolves #148)

### CODE REVIEW

**Comment by mkong0216** [comment]
@meghanhade : should I change the title to "Submit-UI" as discussed in the MOD-walkthrough and get rid of the subtitle text?

**Comment by meghanhade** [comment]
@mkong0216 sure, sounds good 👍

**Comment by hanbyul-here** [comment]
@mkong0216 Hi! I wonder we can split style changes into several PRs rather than one big PR, so that we can see what change the PR is trying to make more clear. (Also prevents conflicts!)

**Comment by mkong0216** [comment]
@hanbyul-here sure I'm fine with that. Yea I was sort of realizing that this is a really long list. 
How would I go about splitting it though? Is there an easy way to split it from this branch or would I have to start over?

**Comment by hanbyul-here** [comment]
@mkong0216 We can start making smaller PRs with left over tasks. Make this PR ready to be merged to master. Work on left over tasks with new pr for each task.

**Pull request closed without merging**
